// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke } from "@tauri-apps/api/core";

export const ipc = {
  /** @throws {string} */
  listConversations(): Promise<Conversation[]> {
    return invoke("list_conversations");
  },
};

/**
 *  One 1:1 conversation, as sent to the frontend list. Field names are
 *  snake_case on both the wire (serde) and in the generated TypeScript
 *  (specta), so the two cannot disagree.
 */
export type Conversation = {
	rowid: number,
	handle: string,
	name: string,
	/**  Last message time as an RFC 3339 string, or null if the chat is empty. */
	last_message: string | null,
	message_count: number,
};
