// This file has been generated by tauri_typed_ipc. DO NOT EDIT.

import { invoke, Channel } from "@tauri-apps/api/core";

export const ipc = {
  checkAccess(): Promise<AccessStatus> {
    return invoke("check_access");
  },

  /** @throws {string} */
  listConversations(): Promise<Conversation[]> {
    return invoke("list_conversations");
  },

  /** @throws {string} */
  exportConversation(rowid: number, outDir: string, start: string | null, end: string | null, onProgress: Channel<ProgressEvent>): Promise<ExportResult> {
    return invoke("export_conversation", { rowid, out_dir: outDir, start, end, on_progress: onProgress });
  },
};

/**  Whether the configured `chat.db` can be read — drives Full Disk Access onboarding. */
export type AccessStatus = "readable" | "denied" | "missing";

/**
 *  One 1:1 conversation, as sent to the frontend list. Field names are
 *  snake_case on both the wire (serde) and in the generated TypeScript
 *  (specta), so the two cannot disagree.
 */
export type Conversation = {
	rowid: number,
	handle: string,
	name: string,
	/**  Last message time as an RFC 3339 string, or null if the chat is empty. */
	last_message: string | null,
	message_count: number,
};

/**  The result of a successful export. */
export type ExportResult = {
	/**  Absolute path of the written PDF. */
	path: string,
};

/**  A streamed progress update during an export. */
export type ProgressEvent = {
	/**  Coarse phase: `preparing` | `building` | `rendering` | `saving`. */
	phase: string,
	/**  Human-readable status for the current step. */
	label: string,
	/**  Completion of the current phase in 0.0–1.0, or null when indeterminate. */
	fraction: number | null,
};
